spring:
  application:
    name: e-commerce
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: root
  pool:
    enabled: true
    max-size: 20
    initial-size: 5
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/kotlin_pg
    user: postgres
    password: root
    locations: classpath:db/migration  # Location of migration scripts
    baseline-on-migrate: true  # Start from the baseline version if schema exists
    clean-disabled: false  # Allow cleaning the database (use carefully)

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,trace"
      health:
        show-detail: always
  health:
    db:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.r2dbc: DEBUG
  file:
    name: src/main/resources/logging/app.log

server:
  reactive:
    netty:
      threads: 100
